[package]
authors = ["Sigurd Holsen <sigurd.holsen@cognite.com>"]
edition = "2018"
name = "clog"
version = "0.5.0"
[dependencies]
chrono = "0.4.19"
color-eyre = "0.5.11"
eyre = "0.6.5"
nom = "6.2.1"
term = "0.7.0"

[dev-dependencies]
proptest = "1.0.0"
proptest-recurse = "0.5.0"
serde_json = "1.0.66"
