[package]
authors = ["Sigurd Holsen <sigurd.holsen@cognite.com>"]
edition = "2018"
name = "clog"
version = "0.5.2"
[dependencies]
chrono = "0.4.19"
color-eyre = "0.5.11"
colored = "2.0.0"
eyre = "0.6.5"
lazy_static = "1.4.0"
nom = "6.2.1"

[dev-dependencies]
proptest = "1.0.0"
proptest-recurse = "0.5.0"
serde_json = "1.0.66"
