[package]
name = "clog"
version = "0.1.0"
authors = ["Sigurd Holsen <sigurd.holsen@cognite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "*"
chrono = "*"
term = "0.6.1"
